--Implement Advanced SQL Joins (Level-1) 
-- From the table PUBLISHER, AUTHOR and BOOK perform the following queries:

SELECT * FROM BOOK
SELECT * FROM AUTHOR
SELECT * FROM PUBLISHER

--Part – A: 
--1. List all books with their authors. 
SELECT TITLE,AUTHORNAME FROM BOOK B
JOIN AUTHOR A
ON B.AUTHORID = A.AUTHORID;

--2. List all books with their publishers. 
SELECT TITLE,P.PUBLISHERNAME FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID = P.PUBLISHERID;

--3. List all books with their authors and publishers. 
SELECT TITLE,P.PUBLISHERNAME,AUTHORNAME FROM BOOK B
JOIN PUBLISHER P
ON P.PUBLISHERID = B.PUBLISHERID
JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID;

--4. List all books published after 2010 with their authors and publisher and price. 
SELECT TITLE,PUBLICATIONYEAR,AUTHORNAME,PUBLISHERNAME FROM BOOK B
JOIN PUBLISHER P
ON P.PUBLISHERID = B.PUBLISHERID
JOIN AUTHOR A
ON A.AUTHORID = B.AUTHORID
WHERE PUBLICATIONYEAR>2010;

--5. List all authors and the number of books they have written. 
SELECT AUTHORNAME,COUNT(BOOKID) AS NO_OF_BOOK FROM BOOK B
JOIN AUTHOR A
ON A.AUTHORID=B.AUTHORID
GROUP BY AUTHORNAME;

--6. List all publishers and the total price of books they have published. 
SELECT PUBLISHERNAME,SUM(PRICE) AS PRICE FROM PUBLISHER P
JOIN BOOK B
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME;

--7. List authors who have not written any books. 
SELECT AUTHORNAME,COUNT(BOOKID) AS NO_OF_BOOK FROM BOOK B
JOIN AUTHOR A
ON A.AUTHORID=B.AUTHORID
GROUP BY AUTHORNAME
HAVING COUNT(BOOKID)=0;

--8. Display the total number of books written by each author along with the average price of their books.
SELECT AUTHORNAME,COUNT(BOOKID) AS NO_OF_BOOK ,AVG(PRICE) AS AVE FROM BOOK B
JOIN AUTHOR A
ON A.AUTHORID=B.AUTHORID
GROUP BY AUTHORNAME;

--9. lists each publisher along with the total number of books they have published, sorted from highest to 
--lowest. 
SELECT PUBLISHERNAME,COUNT(TITLE) AS BOOKS FROM PUBLISHER P
JOIN BOOK B
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME
ORDER BY COUNT(TITLE) DESC;

--10. Display number of books published each year. 
SELECT COUNT(BOOKID) AS NO_OF_BOOK,PUBLICATIONYEAR FROM BOOK B
GROUP BY PUBLICATIONYEAR;

--Part – B: 
--11. List the publishers whose total book prices exceed 500, ordered by the total price. 
SELECT PUBLISHERNAME,SUM(PRICE) AS TOT_PRICE FROM PUBLISHER P 
JOIN BOOK B
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME
HAVING SUM(PRICE)>500
ORDER BY SUM(PRICE);

--12. List most expensive book for each author, sort it with the highest price. 
SELECT MAX(PRICE) AS EXP,AUTHORNAME FROM BOOK B
JOIN AUTHOR A
ON A.AUTHORID=B.AUTHORID
GROUP BY AUTHORNAME
ORDER BY MAX(PRICE) ;

--13. Display publisher name and difference between maximum and minimum book price. 
SELECT PUBLISHERNAME,(MAX(PRICE)-MIN(PRICE)) AS DIFF FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME;

--14. List publisher name and total price of books published each year. 
SELECT PUBLISHERNAME,SUM(PRICE) AS TOT_PRI,PUBLICATIONYEAR FROM BOOK B
JOIN PUBLISHER P
ON B.PUBLISHERID=P.PUBLISHERID
GROUP BY PUBLISHERNAME,PUBLICATIONYEAR;

--15. Display author name and total price of books sorted by highest total price. 
SELECT AUTHORNAME,SUM(PRICE) AS TOT_PRI FROM BOOK B
JOIN AUTHOR A
ON A.AUTHORID=B.AUTHORID
GROUP BY AUTHORNAME
ORDER BY SUM(PRICE) DESC;


--From the above table EMPLOYEE_MASTER perform the following queries:
--Part – C: 
CREATE TABLE EMPLOYEE_MASTER(
EMPLOYEENO CHAR(3),NAME VARCHAR(30),MANAGERNO VARCHAR(30));

INSERT INTO EMPLOYEE_MASTER
VALUES
('E01','TARUN',NULL),
('E02','ROHAN','E02'),
('E03','PRIYA','E01'),
('E04','MILAN','E03'),
('E05','JAY','E01'),
('E06','ANJANA','E04');

SELECT * FROM EMPLOYEE_MASTER;

--16. Retrieve the names of employee along with their manager’s name from the Employee table. 
SELECT E.NAME AS EMP_NAME ,M.NAME AS MAN_NAME
FROM EMPLOYEE_MASTER E
JOIN EMPLOYEE_MASTER M
ON M.EMPLOYEENO=E.MANAGERNO;

--17. Display employees who are managers.
SELECT DISTINCT M.NAME AS MANAGER
FROM EMPLOYEE_MASTER E
JOIN EMPLOYEE_MASTER M
ON M.EMPLOYEENO=E.MANAGERNO;

--18. Display number of employees working under each manager.
SELECT COUNT(E.EMPLOYEENO) AS EMP_UNDER_MAN,M.NAME AS MAN_NAME
FROM EMPLOYEE_MASTER E
JOIN EMPLOYEE_MASTER M
ON M.EMPLOYEENO=E.MANAGERNO
GROUP BY M.NAME;

--19. Display the employee’s name along with their manager’s name and senior manager name.
SELECT E.NAME AS EMP_NAME ,M.NAME AS MAN_NAME,SM.NAME AS SMAN_NAME
FROM EMPLOYEE_MASTER E
JOIN EMPLOYEE_MASTER M
ON M.EMPLOYEENO=E.MANAGERNO
JOIN EMPLOYEE_MASTER SM
ON SM.EMPLOYEENO=M.MANAGERNO;

--20. Display managers and count of employees under them in descending order.
SELECT COUNT(E.EMPLOYEENO) AS EMP_UNDER_MAN,M.NAME AS MAN_NAME
FROM EMPLOYEE_MASTER E
JOIN EMPLOYEE_MASTER M
ON M.EMPLOYEENO=E.MANAGERNO
GROUP BY M.NAME
ORDER BY COUNT(E.EMPLOYEENO) DESC;