--Implement Complex SQL Joins with Multiple Tables and Conditions 
-- From the table DEPARTMENT and PERSON perform the following queries:  
--Part – A: 

SELECT * FROM PERSON
SELECT * FROM DEPARTMENT

--1. Combine information from Person and Department table using cross join or Cartesian product.
SELECT * FROM PERSON
CROSS JOIN DEPARTMENT;

--2. Find all persons with their department name 
SELECT PERSONID,PERSONNAME,DEPARTMENTNAME FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID;

--3. Find all persons with their department name & code. 
SELECT PERSONNAME,PERSONID,DEPARTMENTNAME,DEPARTMENTCODE FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID;

--4. Find all persons with their department code and location.
SELECT DEPARTMENTCODE,PERSONNAME,LOCATION FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID;

--5. Find the detail of the person who belongs to Mechanical department.
SELECT PERSONNAME,DEPARTMENTNAME FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE DEPARTMENTNAME='MECHANICAL';

--6. Final person’s name, department code and salary who lives in Ahmedabad city.  
SELECT PERSONNAME,DEPARTMENTCODE,SALARY,CITY FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE CITY='AHMEDABAD';

--7. Find the person's name whose department is in C-Block.
SELECT PERSONNAME,LOCATION FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE LOCATION='C-BLOCK';

--8. Retrieve person name, salary & department name who belongs to Jamnagar city. 
SELECT PERSONNAME,SALARY,DEPARTMENTNAME,CITY FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE CITY='JAMNAGAR';

--9. Retrieve person’s detail who joined the Civil department after 1-Aug-2001. 
SELECT PERSONNAME,DEPARTMENTNAME,JOININGDATE FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE DEPARTMENTNAME='CIVIL' AND JOININGDATE > '2001-08-01';

--10. Display all the person's name with the department whose joining date difference with the current date 
--is more than 25 years. 
SELECT PERSONNAME,DEPARTMENTNAME,JOININGDATE FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE DATEDIFF(YEAR,JOININGDATE,GETDATE()) > 25;

--11. Find department wise person counts. 
SELECT COUNT(PERSONID) AS CNT,DEPARTMENTNAME FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY DEPARTMENTNAME;

--12. Give department wise maximum & minimum salary with department name. 
SELECT DEPARTMENTNAME,MIN(SALARY) AS MIN_SAL,MAX(SALARY) AS MAX_SAL FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY DEPARTMENTNAME;

--13. Find city wise total, average, maximum and minimum salary. 
SELECT CITY,SUM(SALARY) AS SUM_SAL,AVG(SALARY) AS AVG_SAL,MIN(SALARY) AS MIN_SAL,MAX(SALARY) AS MAX_SAL  FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY CITY;

--14. Find the average salary of a person who belongs to Ahmedabad city. 
SELECT AVG(SALARY) AS AV,CITY FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE CITY='AHMEDABAD'
GROUP BY CITY;

--15. Produce Output Like: <PersonName> lives in <City> and works in <DepartmentName> Department. (In 
--single column) 
SELECT CONCAT(PERSONNAME,' LIVES IN ',CITY,' AND WORKS IN ',DEPARTMENTNAME,' DEPARTMENT') AS CONCAT_COL FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID

--Part – B: 
--16. Produce Output Like: <PersonName> earns <Salary> from <DepartmentName> department monthly. (In 
--single column) 
SELECT CONCAT(PERSONNAME,' EARNS ',SALARY,' FROM ',DEPARTMENTNAME,' DEPARTMENT') FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID;

--17. Find city & department wise total, average & maximum salaries. 
SELECT CITY,DEPARTMENTNAME,SUM(SALARY) AS SUM_SAL,AVG(SALARY) AS AVG_SAL,MAX(SALARY) AS MAX_SAL FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY CITY,DEPARTMENTNAME;

--18. Find all persons who do not belong to any department. 
SELECT PERSONNAME,DEPARTMENTNAME FROM PERSON P
LEFT OUTER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE DEPARTMENTNAME IS NULL;

--19. Find all departments whose total salary is exceeding 100000. 
SELECT DEPARTMENTNAME,SUM(SALARY) AS TOT FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY DEPARTMENTNAME
HAVING SUM(SALARY)>100000;

--Part – C: 
--20. List all departments who have no person.
SELECT DEPARTMENTNAME,COUNT(PERSONNAME) FROM PERSON P
LEFT OUTER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY DEPARTMENTNAME
HAVING COUNT(PERSONNAME)=0;

--21. List out department names in which more than two persons are working. 
SELECT DEPARTMENTNAME,COUNT(PERSONNAME) FROM PERSON P
INNER JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
GROUP BY DEPARTMENTNAME
HAVING COUNT(PERSONNAME)>2;

--22. Give a 10% increment in the computer department employee’s salary. (Use Update)
UPDATE PERSON 
SET SALARY=(SALARY+(SALARY*0.1))
FROM PERSON P JOIN DEPARTMENT D
ON P.DEPARTMENTID=D.DEPARTMENTID
WHERE DEPARTMENTNAME='COMPUTER';