--Implement Advance Common Table Expressions (CTE) for Query Simplification 
-- From the table CUSTOMER perform the following queries:

 CREATE TABLE CUSTOMER_ALL
(
    ORDERID INT,
    CNAME VARCHAR(50),
    PRODUCT VARCHAR(50),
    CATEGORY VARCHAR(50),
    AMOUNT INT,
    ORDERYEAR INT,
    CITY VARCHAR(50)
);

INSERT INTO CUSTOMER_ALL VALUES
(101, 'RAHUL', 'LAPTOP', 'ELECTRONICS', 65000, 2024, 'RAJKOT'),
(102, 'PRIYA', 'MOBILE', 'ELECTRONICS', 25000, 2023, 'SURAT'),
(103, 'AMIT', 'TABLE', 'FURNITURE', 12000, 2022, 'AHMEDABAD'),
(104, 'NEHA', 'CHAIR', 'FURNITURE', 8000, 2024, 'BARODA'),
(105, 'VISHAL', 'TV', 'ELECTRONICS', 45000, 2025, 'MORBI'),
(106, 'RIYA', 'SOFA', 'FURNITURE', 30000, 2023, 'SURAT'),
(107, 'MEHUL', 'AC', 'ELECTRONICS', 40000, 2022, 'RAJKOT'),
(108, 'KRUNAL', 'BED', 'FURNITURE', 40000, 2025, 'JAMNAGAR');

SELECT * FROM CUSTOMER_ALL;

--Part – A: 
--1. Display top 3 highest amount orders.
WITH OD AS
( SELECT *,
DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS DR
FROM CUSTOMER_ALL)
SELECT * FROM OD
WHERE DR<=3;

--2. Display second highest order amount.
WITH OD AS
( SELECT *,
DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS SEC_HIGHEST
FROM CUSTOMER_ALL)
SELECT * FROM OD
WHERE SEC_HIGHEST=2;

--3. Display customers whose order amount is greater than category average amount. 
WITH AV AS
(SELECT *,AVG(AMOUNT) OVER(PARTITION BY CATEGORY) AS ASTU FROM CUSTOMER_ALL)
SELECT * FROM AV
WHERE AMOUNT>ASTU

--4. Display categories having average amount greater than 30000.
WITH AV AS
(SELECT *,AVG(AMOUNT) OVER(PARTITION BY CATEGORY) AS ASTU FROM CUSTOMER_ALL)
SELECT DISTINCT CATEGORY,ASTU FROM AV
WHERE ASTU>30000

--5. Display highest amount order from each category. 
WITH M AS
(SELECT *,
MAX(AMOUNT)
OVER(PARTITION BY CATEGORY
) AS MX
FROM CUSTOMER_ALL)
SELECT DISTINCT CATEGORY,MX FROM M


--6. Display lowest amount order from each category.
WITH M AS
(SELECT *,
MIN(AMOUNT)
OVER(PARTITION BY CATEGORY
) AS MN
FROM CUSTOMER_ALL)
SELECT DISTINCT CATEGORY,MN FROM M

--7. Display categories having more than 3 orders.
WITH CT AS
(SELECT *,COUNT(ORDERID) OVER(PARTITION BY CATEGORY
) AS C
FROM CUSTOMER_ALL)
SELECT DISTINCT CATEGORY,C FROM CT
WHERE C>3

--8. Display city-wise total order amount. 
WITH CT AS
(SELECT *,SUM(AMOUNT) OVER(PARTITION BY CITY
) AS C
FROM CUSTOMER_ALL)
SELECT DISTINCT CITY,C FROM CT

--9. Display category having highest average order amount.
WITH AV AS
(SELECT *,AVG(AMOUNT) OVER(PARTITION BY CATEGORY) AS ASTU FROM CUSTOMER_ALL)
SELECT  TOP 1 ASTU,CATEGORY FROM AV

--10. Display cumulative order amount in ascending order of amount. 
 WITH T AS
(
 SELECT *,
 SUM(AMOUNT) OVER
 (
 ORDER BY AMOUNT
 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
 ) AS [Cumulative Amount]
 FROM CUSTOMER_ALL
)
SELECT *
FROM T
ORDER BY AMOUNT;

--Part – B: 
--11. Display category-wise top 2 highest amount orders.
WITH OD AS
(SELECT *,
DENSE_RANK() OVER(
PARTITION BY CATEGORY
ORDER BY AMOUNT DESC) AS DR
FROM CUSTOMER_ALL)
SELECT DISTINCT CATEGORY,DR FROM OD
WHERE DR<=2;

--12. Display customers whose amount is closest to category average amount. 
WITH AV AS
(SELECT *,ABS(AMOUNT-AVG(AMOUNT) OVER(PARTITION BY CATEGORY)) AS DIFF 
FROM CUSTOMER_ALL)
SELECT MIN(DIFF) AS LEAST_AVG FROM AV

--13. Display previous, current and next order amount together. 
WITH THREE AS
(SELECT LAG(AMOUNT) OVER(ORDER BY ORDERID) AS LG, LEAD(AMOUNT) OVER(ORDER BY ORDERID) AS LD,AMOUNT FROM CUSTOMER_ALL)
SELECT * FROM THREE

--14. Display customers whose amount is greater than previous customer's amount.
WITH GT AS
(SELECT LAG(AMOUNT) OVER(ORDER BY ORDERID) AS LG,AMOUNT
FROM CUSTOMER_ALL)
SELECT * FROM GT
WHERE LG<AMOUNT 

--15. Display customers whose rank and dense rank are different. 
 WITH OD AS
( SELECT *,
DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS DR,
RANK() OVER(ORDER BY AMOUNT DESC) AS R
FROM CUSTOMER_ALL)
SELECT * FROM OD
WHERE DR!=R;

--Part – C: 
--16. Display orders whose amount is neither highest nor lowest in their category. 
WITH M AS
(SELECT *,
MAX(AMOUNT)
OVER(PARTITION BY CATEGORY
) AS MX,
MIN(AMOUNT)
OVER(PARTITION BY CATEGORY
) AS MN
FROM CUSTOMER_ALL)
SELECT * FROM M
WHERE AMOUNT!=MX AND AMOUNT!=MN

--17. Display category-wise difference between highest and lowest amount.
WITH M AS
(SELECT *,
MAX(AMOUNT)
OVER(PARTITION BY CATEGORY
) AS MX,
MIN(AMOUNT)
OVER(PARTITION BY CATEGORY
) AS MN
FROM CUSTOMER_ALL)
SELECT DISTINCT CATEGORY,MX,MN FROM M

--18. Display customers whose amount is greater than all FURNITURE category orders.
WITH M AS
(SELECT *,
SUM(AMOUNT) OVER(PARTITION BY CATEGORY
) AS S
FROM CUSTOMER_ALL
WHERE CATEGORY='FURNITURE')
SELECT * FROM M
WHERE AMOUNT>S;

--19. Display categories where all orders are above 10000.
WITH M AS
(SELECT *,
MIN(AMOUNT)
OVER(PARTITION BY CATEGORY
) AS MN
FROM CUSTOMER_ALL)
SELECT DISTINCT CATEGORY,MN FROM M
WHERE MN>10000;

--20. Display customers whose amount difference from category topper is minimum. 
WITH M AS (
    SELECT *, 
           MAX(AMOUNT) OVER(PARTITION BY CATEGORY) AS MX, 
           ABS(AMOUNT - MAX(AMOUNT) OVER(PARTITION BY CATEGORY)) AS DIFF 
    FROM CUSTOMER_ALL
) 
SELECT * FROM M 
WHERE DIFF = (SELECT MIN(DIFF) FROM M);